# .goreleaser.yml
version: 2
release:
  disable: false
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm
